services:
  - type: web
    name: psa-portal
    env: node
    region: singapore
    plan: free
    buildCommand: "npm install --build-from-source && node server/migrate.js"
    startCommand: "node server/index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.1
